import 'package:flutter_test/flutter_test.dart';
import 'package:shawyer_words/features/dictionary/application/dictionary_controller.dart';
import 'package:shawyer_words/features/dictionary/domain/dictionary_import_result.dart';
import 'package:shawyer_words/features/dictionary/domain/dictionary_package.dart';
import 'package:shawyer_words/features/dictionary/domain/dictionary_repository.dart';
import 'package:shawyer_words/features/dictionary/domain/dictionary_summary.dart';
import 'package:shawyer_words/features/dictionary/domain/word_entry.dart';
import 'package:shawyer_words/features/study/domain/study_repository.dart';

void main() {
  test('import success exposes the first entry', () async {
    final controller = DictionaryController(
      dictionaryRepository: _FakeDictionaryRepository(),
      studyRepository: _FakeStudyRepository(),
    );

    await controller.importDictionary('/tmp/test.mdx');

    expect(controller.state.status, DictionaryStatus.ready);
    expect(controller.state.dictionary?.name, 'Test Dictionary');
    expect(controller.state.activePackage?.name, 'Oxford Starter');
    expect(controller.state.activePackage?.type, DictionaryPackageType.imported);
    expect(controller.state.currentEntry?.word, 'abandon');
    expect(controller.state.entries, hasLength(2));
  });

  test('import failure exposes a clean unsupported message', () async {
    final controller = DictionaryController(
      dictionaryRepository: _FailingDictionaryRepository(),
      studyRepository: _FakeStudyRepository(),
    );

    await controller.importDictionary('/tmp/legacy.mdx');

    expect(controller.state.status, DictionaryStatus.failure);
    expect(controller.state.activePackage, isNull);
    expect(
      controller.state.errorMessage,
      'This app currently only supports MDX dictionaries generated by engine version 2.0 or newer.',
    );
  });
}

class _FakeDictionaryRepository implements DictionaryRepository {
  @override
  Future<DictionaryImportResult> importDictionary(String filePath) async {
    return DictionaryImportResult(
      package: const DictionaryPackage(
        id: 'oxford-starter',
        name: 'Oxford Starter',
        type: DictionaryPackageType.imported,
        rootPath: '/tmp/dictionaries/imported/oxford-starter',
        mdxPath: '/tmp/dictionaries/imported/oxford-starter/source/main.mdx',
        mddPaths: <String>[],
        resourcesPath: '/tmp/dictionaries/imported/oxford-starter/resources',
        importedAt: '2026-03-16T00:00:00.000Z',
        entryCount: 2,
      ),
      dictionary: const DictionarySummary(
        id: 'dict-1',
        name: 'Test Dictionary',
        sourcePath: '/tmp/dictionaries/imported/oxford-starter',
        importedAt: '2026-03-16T00:00:00.000Z',
        entryCount: 2,
      ),
      entries: const [
        WordEntry(
          id: '1',
          word: 'abandon',
          pronunciation: '/əˈbændən/',
          partOfSpeech: 'verb',
          definition: 'to leave behind',
          exampleSentence: 'They abandon the plan at sunrise.',
          rawContent: '<p>abandon</p>',
        ),
        WordEntry(
          id: '2',
          word: 'brisk',
          definition: 'quick and energetic',
          rawContent: '<p>brisk</p>',
        ),
      ],
    );
  }
}

class _FakeStudyRepository implements StudyRepository {
  @override
  Future<void> saveDecision({
    required String entryId,
    required StudyDecisionType decision,
  }) async {}
}

class _FailingDictionaryRepository implements DictionaryRepository {
  @override
  Future<DictionaryImportResult> importDictionary(String filePath) {
    throw UnsupportedError(
      'This app currently only supports MDX dictionaries generated by engine version 2.0 or newer.',
    );
  }
}
